services:
  nginx:
    image: nginx:latest
    container_name: learn-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/conf.d/CONF_FILE:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4

  app1:
    build:
      context: ./servers
      dockerfile: Dockerfiles/Dockerfile.server1
    image: server-1:latest
    ports:
      - "3001:3000"

  app2:
    build:
      context: ./servers
      dockerfile: Dockerfiles/Dockerfile.server2
    image: server-2:latest
    ports:
      - "3002:3000"

  app3:
    build:
      context: ./servers
      dockerfile: Dockerfiles/Dockerfile.server3
    image: server-3:latest
    ports:
      - "3003:3000"

  app4:
    build:
      context: ./servers
      dockerfile: Dockerfiles/Dockerfile.server4
    image: server-4:latest
    ports:
      - "3004:3000"